---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config-v1
  namespace: security
  labels:
    app.kubernetes.io/name: &name vaultwarden
    app.kubernetes.io/instance: *name
    pmb.home.arpa/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
