---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ananace-charts.yaml
- authentik-charts.yaml
- bitnami-charts.yaml
- blakeshome-charts.yaml
- coredns-charts.yaml
- deliveryhero-charts.yaml
- drone-charts.yaml
- fairwinds-charts.yaml
- falco-security-charts.yaml
- grafana-charts.yaml
- infracloudio-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- kubernetes-sigs-descheduler-charts.yaml
- lwolf-charts.yaml
- mailu-charts.yaml
- nfs-subdir-external-provisioner-charts.yaml
- node-feature-discovery-charts.yaml
- nvidia-charts.yaml
- prometheus-community-charts.yaml
- rook-ceph-charts.yaml
- stakater-charts.yaml
- hajimari-charts.yaml
- traefik-charts.yaml
- uptimerobot-operator-charts.yaml
- vernemq-charts.yaml
- weaveworks-kured-charts.yaml
