---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: toboshii-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://toboshii.github.io/helm-charts
  timeout: 3m
