---

# Use Calico CNI driver
calico:
  enabled: true
  operator_manifest: "https://docs.projectcalico.org/manifests/tigera-operator.yaml"
  # Enabling BGP requires your router set up to handle it
  bgp:
    enabled: true
    # peer is usually your router e.g. 192.168.1.1
    peer: 10.75.40.1
    as: 64512
    # externalIPs is the network you want services to consume
    # this network should not exist or be defined anywhere in your network
    # e.g. 192.168.169.0/24
    externalIPs: 10.75.45.0/24
  node:
    cidrs: 
    - 10.75.40.0/24
    - 10.75.30.0/24