---

# - hosts:
#   - master-nodes
#   - worker-nodes
#   - gpu-nodes
#   become: true
#   gather_facts: true
#   any_errors_fatal: true
#   pre_tasks:
#   - name: Pausing for 5 seconds...
#     pause:
#       seconds: 5
#   roles:
#   - kube_vip
#   - xanmanning.k3s
#   - k3s

- hosts:
  - gpu-nodes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
  - name: Pausing for 5 seconds...
    pause:
      seconds: 5
  roles:
  - nvidia
