---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: "cluster-0"
  CLUSTER_ID: "1"
  CONTROL_PLANE_ENDPOINT: "cluster-0.dfw.56k.sh"
  GATEWAY_IP: 10.75.0.1
  NETWORK_K8S_CLUSTER_CIDR: 172.22.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 172.24.0.0/16
  NETWORK_MANAGEMENT_CIDR: 10.0.0.0/8
  METALLB_LB_RANGE: 10.75.42.100-10.75.42.120
  LB_COREDNS_IP: 10.75.45.100
  LB_TRAEFIK_IP: 10.75.45.101
  LB_LOKI_IP: 10.75.45.102
  LB_PLEX_IP: 10.75.45.103
  LB_JELLYFIN_IP: 10.75.45.104
  LB_BLOCKY_IP: 10.75.45.105
  LB_QBITTORRENT_IP: 10.75.45.106
  LB_OWNCAST_IP: 10.75.45.107
