---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - _pvc
  # - lidarr
  # - overseerr
  # - prowlarr
  # - qbittorrent
  # - radarr
  # - sabnzbd
  - sonarr
