apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico-system
- falco-system
- flux-system
- kasten-io
- kube-system
- media
- monitoring
- networking
- security
- system-upgrade
