---

- name: driver | blacklist nouveau driver
  ansible.builtin.copy:
    src: files/blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
  register: blacklist

- name: driver | update initramfs
  ansible.builtin.command: "update-initramfs -u"
  when: blacklist.changed

- name: driver | reboot to unload nouveau
  ansible.builtin.reboot:
  when: blacklist.changed

- name: driver | install dkms build tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
  - "dkms"
  - "build-essential"

- name: driver | download nvidia driver
  ansible.builtin.get_url:
    url: https://international.download.nvidia.com/XFree86/Linux-x86_64/465.27/NVIDIA-Linux-x86_64-{{ nvidia_driver.version }}.run
    dest: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_driver.version }}.run
    checksum: "{{ nvidia_driver.checksum }}"
    mode: '0755'

- name: driver | install nvidia driver
  ansible.builtin.command:
    cmd: "/tmp/NVIDIA-Linux-x86_64-{{ nvidia_driver.version }}.run -s --no-opengl-files"
    creates: "/proc/driver/nvidia/version"

- name: driver | load nvidia driver
  modprobe:
    name: nvidia
    state: present
