---
name: Create diff on updated HelmReleases

on:
  pull_request:
    branches:
      - main
    paths:
      - "cluster/**.yaml"

env:
  conf_live_branch: main
  conf_allow_repeating_same_comment: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      files: "${{ steps.extract.outputs.files }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changed:
              - '**'
      - name: Keep HelmReleases only
        id: extract
        run: |
          filtered=$(grep -zl "kind: HelmRelease.*registryUrl=" ${{ steps.filter.outputs.changed_files }} | \
            jq -R '[.]' | \
            jq -s -c add)
          echo ::set-output name=files::${filtered}

  helm:
    name: Template HelmReleases
    runs-on: ubuntu-latest
    needs:
      - changes
    strategy:
      matrix:
        file: ${{ fromJson(needs.changes.outputs.files) }}
      fail-fast: false
    steps:
      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: |
            helmv3
            yq
      - name: Checkout live branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.conf_live_branch }}
          path: live
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          path: pr
      - name: Create diff
        id: diff
        run: |
          hr_live_url=$(sed -nr 's|.*registryUrl=(.+)$|\1|p' live/${{ matrix.file }})
          hr_live_chart=$(yq e .spec.chart.spec.chart live/${{ matrix.file }})
          hr_live_version=$(yq e .spec.chart.spec.version live/${{ matrix.file }})
          hr_live_values=$(yq e .spec.values live/${{ matrix.file }})

          hr_pr_url=$(sed -nr 's|.*registryUrl=(.+)$|\1|p' pr/${{ matrix.file }})
          hr_pr_chart=$(yq e .spec.chart.spec.chart pr/${{ matrix.file }})
          hr_pr_version=$(yq e .spec.chart.spec.version pr/${{ matrix.file }})
          hr_pr_values=$(yq e .spec.values pr/${{ matrix.file }})

          helm repo add live "$hr_live_url"
          helm repo add pr "$hr_pr_url"

          resources_live=$(echo "$hr_live_values" | \
            helm template "$hr_live_chart" \
            live/"$hr_live_chart" \
            --version "$hr_live_version" -f -)
          echo "$resources_live"
          echo "#####################################################"

          resources_pr=$(echo "$hr_pr_values" | \
            helm template "$hr_pr_chart" \
            pr/"$hr_pr_chart" \
            --version "$hr_pr_version" -f -)
          echo "$resources_pr"
          echo "#####################################################"

          diff=$((diff -u <(echo "$resources_live") <(echo "$resources_pr") || true) | tail +3)
          echo "$diff"

          message="Path: \`${{ matrix.file }}\`"
          if [ "$hr_live_chart" != "$hr_pr_chart" ]; then
            message="$message"$'\n'"Chart: \`$hr_live_chart\` -> \`$hr_pr_chart\`"
          fi
          if [ "$hr_live_version" != "$hr_pr_version" ]; then
            message="$message"$'\n'"Version: \`$hr_live_version\` -> \`$hr_pr_version\`"
          fi
          if [ "$hr_live_url" != "$hr_pr_url" ]; then
            message="$message"$'\n'"Repo: \`$hr_live_url\` -> \`$hr_pr_url\`"
          fi
          message="$message"$'\n'$'\n'
          if [ -z "$diff" ]; then
            message="$message"'```'$'\n'"No changes in detected in resources"$'\n''```'
          else
            message="$message"'```diff'$'\n'"$diff"$'\n''```'
          fi

          echo "::set-output name=message::$(echo "$message" | jq --raw-input --slurp)"

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: ${{ env.conf_allow_repeating_same_comment }}
          message: "${{ fromJSON(steps.diff.outputs.message) }}"
